services:
  - type: web
    name: gold-bot-bingx
    env: python
    plan: free
    autoDeploy: true

    buildCommand: pip install -r requirements.txt
    startCommand: python "dhb bingx.py"

    envVars:
      - key: EXCHANGE
        value: bingx
      - key: SYMBOL
        value: XAU/USDT
      - key: RISK_ALLOC
        value: 0.30
      - key: LEVERAGE
        value: 10
      - key: POSITION_MODE
        value: oneway
      - key: PORT
        value: 5000

      - key: BINGX_API_KEY
        sync: false
      - key: BINGX_API_SECRET
        sync: false
      - key: BINGX_TESTNET
        value: "0"
