
  - type: web
    name: sol-bybit-bot          # خليه نفس الاسم القديم
    env: python
    plan: free
    autoDeploy: true

    buildCommand: pip install -r requirements.txt
    startCommand: python "dhb bingx.py"   # غيّرها لاسم سكربت الذهب عندك لو مختلف

    envVars:
      - key: EXCHANGE
        value: bingx
      - key: SYMBOL
        value: XAU/USDT
      - key: TIMEFRAME
        value: 15m
      - key: POSITION_MODE
        value: oneway
      - key: LEVERAGE
        value: 10
      - key: RISK_ALLOC
        value: 0.30
      - key: PORT
        value: 5000

      # مفاتيح BingX بالأسماء اللي الكود بيقرأها
      - key: API_KEY          # أو BINGX_API_KEY لو الكود بيستخدمها
        sync: false
      - key: API_SECRET       # أو BINGX_API_SECRET
        sync: false

      # اختياري
      - key: FINAL_CHUNK_QTY
        value: "2.0"
      - key: WAIT_NEXT_SIGNAL
        value: "1"
      - key: LOOP_SLEEP_SEC
        value: "6.0"
